package ruben.hernandez.rentalcar.views.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0x0FBB216A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF406FDC)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF8C5004)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFEAE60)
val onSecondaryContainerLight = Color(0xFF4C2800)
val tertiaryLight = Color(0xFF006D42)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF5FF9AA)
val onTertiaryContainerLight = Color(0xFF005030)
val errorLight = Color(0xFF9E1822)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFD13F42)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF191B22)
val surfaceLight = Color(0xFFFDF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFB2C5FF)
val surfaceDimLight = Color(0xFFDDD9D8)
val surfaceBrightLight = Color(0xFFFDF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)



val primaryDark = Color(0xFFB2C5FF)
val onPrimaryDark = Color(0xFF002B73)
val primaryContainerDark = Color(0xFF406FDC)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFD1A9)
val onSecondaryDark = Color(0xFF4B2800)
val secondaryContainerDark = Color(0xFFEC9F53)
val onSecondaryContainerDark = Color(0xFF3B1E00)
val tertiaryDark = Color(0xFFFEFFFA)
val onTertiaryDark = Color(0xFF003920)
val tertiaryContainerDark = Color(0xFF52EEA1)
val onTertiaryContainerDark = Color(0xFF00492B)
val errorDark = Color(0xFFFFB3AF)
val onErrorDark = Color(0xFF68000D)
val errorContainerDark = Color(0xFFD13F42)
val onErrorContainerDark = Color(0xFFFFFFFF)
val backgroundDark = Color(0xFF11131A)
val onBackgroundDark = Color(0xFFE2E2EB)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C8)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF2258C4)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)







